-   name: Create AWS instances
    hosts: localhost
    connection: local
    gather_facts: False
    remote_user: ubuntu
    roles:
        - provision

-   name: Add user keys
    hosts: ec2_hosts
    sudo: yes
    sudo_user: root
    remote_user: ubuntu
    roles:
        - users
